### PR TITLE
New Ore Glow

### PR DESCRIPTION
**Pull request by supsm**
Changes ore glow so it looks different
also adds ore glow to iron and copper

technically you already gave me approval

### CODE REVIEW

**Comment by ambrosia13** [comment]
I'll probably have time to look this over in a few days. One thing I notice, though, is that some things you're doing operations with are integers when they should be floats. It mostly doesn't cause issues but I feel like it's best practice to stick with floats when working with floats.

Also, in some of your checks you check if frx_fragColor is some value over one. This isn't possible because before the material shader runs, it should be between 0.0 and 1.0.

In any case, thank you for sorting this out - a few days ago I was experimenting with iron checks but couldn't quite get it done right.

**Comment by ambrosia13** [comment]
Okay, ignore the second comment. I took a closer look and you aren't actually doing what I thought you were.

**Comment by supsm** [comment]
I just changed ints to floats. I thought it wouldn’t really matter since it would be converted to float anyways, but if you would like it this way that’s fine with me. Do you need me to add parentheses so it’s more clear what I’m trying to accomplish?

**Comment by ambrosia13** [comment]
No, this looks good. I'll test it when I can and hopefully merge it. Thank you.

**Comment by ambrosia13** [comment]
It looks good, merging.

**Pull request merged**
